service: thepapare-stats-cricket

provider:
  name: aws
  runtime: nodejs8.10

functions:
  teamsAll:
    handler: handler.teamsAll
    events:
    - http:
        path: teams
        method: get

plugins:
  - serverless-offline